### PR TITLE
remove execUtilClone and use new common lib

### PR DESCRIPTION
**Pull request by lstocchi**
This needs https://github.com/redhat-developer/intellij-common/pull/108 to work

It removes the ExecUtilClone class and uses the last common lib with the new terminal implementation (the older one will be deprecated from 2021.3 so we need to switch). I tested it and it seems to work for me. 
@adietish It would be good if you could test it on macOS to see if we have the right behavior there as well

### CODE REVIEW

**Comment by adietish** [comment]
@lstocchi: This doesn't compile for me even if I change the required common to intellij-common 1.4.0-SNAPSHOT. What am I missing? 
```
/Users/andredietisheim/Documents/jboss-workspaces/intellij-rsp/src/main/java/com/redhat/devtools/intellij/rsp/model/impl/RspCore.java:295: error: incompatible types: RspProcessHandler cannot be converted to Process
                ExecHelper.linkProcessToTerminal(new RspProcessHandler(p,name, "run server " + name), project, name,false);
                                                 ^
```
I also think that we should move the minimum version 2018.3 -> 2019.3 which is the minimum across all our plugins now.

**Comment by lstocchi** [comment]
> @lstocchi: This doesn't compile for me even if I change the required common to intellij-common 1.4.0-SNAPSHOT. What am I missing?
> 
> ```
> /Users/andredietisheim/Documents/jboss-workspaces/intellij-rsp/src/main/java/com/redhat/devtools/intellij/rsp/model/impl/RspCore.java:295: error: incompatible types: RspProcessHandler cannot be converted to Process
>                 ExecHelper.linkProcessToTerminal(new RspProcessHandler(p,name, "run server " + name), project, name,false);
>                                                  ^
> ```

Are you sure you're using this PR? Can you re-try? That line doesn't exist anymore. RspProcessHandler was defined inside ExecUtilClone which was deleted.
I also bumped the ij-common lib to 1.4.0-SNAPSHOT yesterday morning so you shouldn't change it. If you don't have it you are not using the latest version.

> I also think that we should move the minimum version 2018.3 -> 2019.3 which is the minimum across all our plugins now.

Right, done :+1:

**Comment by adietish** [comment]
@lstocchi my bad, I was - as you suggested - on a bad branch which wasn't properly updated. Now that I am on the correct one things seem work basically fine for me. I found an issue though that I cannot replicate in master branch:

**Steps:**
1. EXEC: start rsp
1. EXEC: start wildfly 24.0.1
2. EXEC: stop wildfly
3. EXEC: quit IJ

**Result:**
Dialog pops up informing you that wildfy/rsp are still running and IJ is waiting for a successful kill
wildfly-is-not-stopped. The dialog never goes away, IJ keeps waiting.

 I think that this may be related to the notification that the original code had and that's now not present any more.
@lstocchi, @robstryker thoughts?

**Comment by lstocchi** [comment]
> **Result:** Dialog pops up informing you that wildfy/rsp are still running and IJ is waiting for a successful kill wildfly-is-not-stopped. The dialog never goes away, IJ keeps waiting.
> 
> I think that this may be related to the notification that the original code had and that's now not present any more. @lstocchi, @robstryker thoughts?

Replicated. I can see a NPE inside the IJ console when trying to stop all processes. Investigating...

**Comment by lstocchi** [comment]
@adietish fixed the issue of the processes kept opened after being stopped. Can you please re-test? Thanks

**Comment by adietish** [comment]
@lstocchi awesomeness! things work nicely for me, can't replicate the issue any more. Good to go!

**Comment by lstocchi** [comment]
> @lstocchi awesomeness! things work nicely for me, can't replicate the issue any more. Good to go!

Yay!! Now the final boss @robstryker :laughing:

**Comment by robstryker** [comment]
will investigate it. Thanks guys.

**Pull request merged**
